name: CD images

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - name: Build and push API
        uses: docker/build-push-action@v6
        with:
          context: apps/api
          file: apps/api/Dockerfile
          push: true
          tags: |
            ghcr.io/jasensic/my-drive-api:latest
            ghcr.io/jasensic/my-drive-api:${{ github.sha }}
      - name: Build and push web
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/web/Dockerfile
          push: true
          tags: |
            ghcr.io/jasensic/my-drive-web:latest
            ghcr.io/jasensic/my-drive-web:${{ github.sha }}
